### ISSUE TITLE
ebusd hmu state energy, wrong device class should be percentage instead of energy

### ISSUE THREAD

**Issue by garageboxnv** [john30/ebusd-configuration#498]
Using hassio mqtt integration gives me following error:
```
Entity sensor.ebusd_hmu_state_energy (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['mWh', 'GJ', 'GWh', 'TWh', 'J', 'Gcal', 'cal', 'MWh', 'Wh', 'kWh', 'kJ', 'Mcal', 'kcal', 'MJ']
```

According to my knowledge this ebusd value represents the compressor speed in percentage, not related to energy values.

mqtt hassio state topic
```
unique_id: ebusd_hmu_State_energy
device:
  identifiers: ebusd_hmu
  manufacturer: ebusd.eu
  via_device: ebusd
  sw_version: '24.1'
  suggested_area: Heating
  name: ebusd hmu
value_template: '{{value_json["energy"].value}}'
state_topic: ebusd/hmu/State
state_class: total_increasing
device_class: energy
name: State energy
```
Data from home assistant which shows only toggle between 0 and 100, due to my flexotherm exclusive heatpump. Still want to figure out if I can configure it lower to be able to adapt the speed in relation with my generated PV energy.

```
entity_id,state,last_changed
sensor.ebusd_hmu_state_energy,0,2025-04-18T22:00:00.000Z
sensor.ebusd_hmu_state_energy,100,2025-04-19T03:03:09.510Z
sensor.ebusd_hmu_state_energy,0,2025-04-19T03:56:39.501Z
sensor.ebusd_hmu_state_energy,100,2025-04-19T04:13:39.497Z
```
