### ISSUE TITLE
ebusd pms internalhctempdesired and internalhwctempdesired missing unit of measurement

### ISSUE THREAD

**Issue by garageboxnv** [john30/ebusd-configuration#499]
Using hassio mqtt integration gives me following errors:
```
sensor.ebusd_pms_internalhctempdesired (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['°C', 'K', '°F']

sensor.ebusd_pms_internalhwctempdesired (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['°C', 'K', '°F']
```
mqtt hassio state topics
```
unique_id: ebusd_pms_InternalHcTempDesired_value
device:
  identifiers: ebusd_pms
  manufacturer: ebusd.eu
  via_device: ebusd
  sw_version: '24.1'
  suggested_area: Heating
  name: ebusd pms
value_template: '{{value_json["value"].value}}'
state_topic: ebusd/pms/InternalHcTempDesired
state_class: measurement
device_class: temperature
name: 'InternalHcTempDesired '

unique_id: ebusd_pms_InternalHwcTempDesired_value
device:
  identifiers: ebusd_pms
  manufacturer: ebusd.eu
  via_device: ebusd
  sw_version: '24.1'
  suggested_area: Heating
  name: ebusd pms
value_template: '{{value_json["value"].value}}'
state_topic: ebusd/pms/InternalHwcTempDesired
state_class: measurement
device_class: temperature
name: 'InternalHwcTempDesired '
```
I also wonder if this is the proper value as I have always following values:
```
entity_id,state,last_changed
sensor.ebusd_pms_internalhctempdesired,128,2025-04-17T22:00:00.000Z

entity_id,state,last_changed
sensor.ebusd_pms_internalhwctempdesired,16,2025-04-17T22:00:00.000Z
```
