### ISSUE TITLE
ebusd hwc mctype 9 unkown

### ISSUE THREAD

**Issue by garageboxnv** [john30/ebusd-configuration#500]
Using hassio mqtt integration gives me following error:
```
Ignoring invalid option received on topic 'ebusd/hwc/Mode', got '9', allowed: inactive, mixer, fixed, hwc, returnincr, pool, circulation
```
I have an vaillant aguaflow exclusive, I expect mode 9 might indicate that the mctype is a "buffercircuit"

mqtt hassio state topic
```
unique_id: ebusd_hwc_Mode_mctype
device:
  identifiers: ebusd_hwc
  manufacturer: ebusd.eu
  via_device: ebusd
  sw_version: '24.1'
  suggested_area: Heating
  name: ebusd hwc
value_template: '{{value_json["mctype"].value}}'
state_topic: ebusd/hwc/Mode
device_class: enum
options:
  - inactive
  - mixer
  - fixed
  - hwc
  - returnincr
  - pool
  - circulation
name: Mode mctype
```
value received
```
Received 08:31:48

    QoS: 0, Retained
    Payload:

    temp:
      value: 47
    hwcmode:
      value: auto
    hwcmode_1:
      value: disabled
    mctype:
      value: 9
    hex:
      value: '00'
    daynight:
      value: night
```
