### ISSUE TITLE
ebusd hmu runstatuscode 0 unknown

### ISSUE THREAD

**Issue by garageboxnv** [john30/ebusd-configuration#501]
Using hassio mqtt integration gives me following error:
``
Ignoring invalid option received on topic 'ebusd/hmu/RunDataStatuscode', got '0', allowed: Frost_protection, Standby, Heating_Compressor_shutdown, Heating_Compressor_blocked, Heating_Prerun, Heating_Compressor_active, Heating_Overrun, Cooling_Compressor_shutdown, Cooling_Compressor_blocked, Cooling_Prerun, Cooling_Compressor_active, Cooling_Overrun, Heating_Immersion_heater_active, Warm_Water_Compressor_blocked, Warm_Water_Prerun, Warm_Water_Compressor_active, Warm_Water_Immersion_Heater_active, Warm_Water_Overrun, Heating_Immersion_Heater_shutdown, Heating_Immersion_Heater_blocked, Warm_Water_Immersion_Heater_shutdown, Warm_Water_Immersion_Heater_blocked, Air_purging_program_active, Compressor_oil_heating_activated, Fan_1_blocked, Fan_1_air_inlet_too_high, Fan_1_air_inlet_too_low, Fan_2_blocked, Building_circuit_flow_too_low, Building_circuit_pump_fault, Frequency_converter_fault_Compressor, Frequency_converter_fault_Mains_voltage, Frequency_converter_fault_Overheating, Deicing_time_too_long, Deicing_flow_temperature_too_low, Compressor_outlet_temperature_too_high, Hot_gas_temperature_switch_open, Fan_1_Wind, Fan_2_Wind, Current_limt_active, High_pressure_switch_open, Compressor_outlet_temperature_too_high_1, Evaporation_temperature_too_low, Condensation_temperature_too_low, Evaporation_temperature_too_high, Condensation_temperature_too_high, Building_circuit_return_temperature_too_low, Building_circuit_return_temperature_too_high, Immersion_heater_Flow_temperature_too_high, Deicing_active, Frequency_converter_fault, Connection_fault_frequency_converter, _4_port_valve_position_fault
``
I have a flexotherm exclusive vwf

mqtt hassio state topic
```
unique_id: ebusd_hmu_RunDataStatuscode_value
device:
  identifiers: ebusd_hmu
  manufacturer: ebusd.eu
  via_device: ebusd
  sw_version: '24.1'
  suggested_area: Heating
  name: ebusd hmu
value_template: '{{value_json["value"].value}}'
state_topic: ebusd/hmu/RunDataStatuscode
device_class: enum
options:
  - Frost_protection
  - Standby
  - Heating_Compressor_shutdown
  - Heating_Compressor_blocked
  - Heating_Prerun
  - Heating_Compressor_active
  - Heating_Overrun
  - Cooling_Compressor_shutdown
  - Cooling_Compressor_blocked
  - Cooling_Prerun
  - Cooling_Compressor_active
  - Cooling_Overrun
  - Heating_Immersion_heater_active
  - Warm_Water_Compressor_blocked
  - Warm_Water_Prerun
  - Warm_Water_Compressor_active
  - Warm_Water_Immersion_Heater_active
  - Warm_Water_Overrun
  - Heating_Immersion_Heater_shutdown
  - Heating_Immersion_Heater_blocked
  - Warm_Water_Immersion_Heater_shutdown
  - Warm_Water_Immersion_Heater_blocked
  - Air_purging_program_active
  - Compressor_oil_heating_activated
  - Fan_1_blocked
  - Fan_1_air_inlet_too_high
  - Fan_1_air_inlet_too_low
  - Fan_2_blocked
  - Building_circuit_flow_too_low
  - Building_circuit_pump_fault
  - Frequency_converter_fault_Compressor
  - Frequency_converter_fault_Mains_voltage
  - Frequency_converter_fault_Overheating
  - Deicing_time_too_long
  - Deicing_flow_temperature_too_low
  - Compressor_outlet_temperature_too_high
  - Hot_gas_temperature_switch_open
  - Fan_1_Wind
  - Fan_2_Wind
  - Current_limt_active
  - High_pressure_switch_open
  - Compressor_outlet_temperature_too_high_1
  - Evaporation_temperature_too_low
  - Condensation_temperature_too_low
  - Evaporation_temperature_too_high
  - Condensation_temperature_too_high
  - Building_circuit_return_temperature_too_low
  - Building_circuit_return_temperature_too_high
  - Immersion_heater_Flow_temperature_too_high
  - Deicing_active
  - Frequency_converter_fault
  - Connection_fault_frequency_converter
  - _4_port_valve_position_fault
name: 'RunDataStatuscode '
```
value received

```
Received 08:31:48

    QoS: 0, Retained
    Payload:

    value:
      value: 0
```
